config/routes.rb
Depot::Application.routes.draw do
  get 'admin' => 'admin#index', :as => 'admin'

  controller :sessions do
    get 'login'     => :new
    post 'login'    => :create
    delete 'logout' => :destroy
  end

  resources :users

  resources :orders

  resources :line_items do
    put 'decrease', on: :member
    put 'increase', on: :member
  end

  resources :carts

  get "store/index"

  resources :products do
    get :who_bought, :on => :member
  end

   root :to => 'store#index', :as => 'store'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
	#A cart has many items in the cart
	#The existence of line_items is dependent on the existence of the cart.
	has_many :line_items, :dependent => :destroy

	def add_product(product_id)
		#Try and find the line item in the current cart based
		#on the product ID.
		#Active record is smart enough to know "find_by" and
		#ending in the column name of line_items. It searches.
		current_item = line_items.find_by_product_id(product_id)
		#If the product ID is found then add to the quantity
		if current_item
			current_item.quantity += 1
		#if the product ID is not found, then build the product
		else
			#Pass the product that was found into "build"
    		#this causes new line item relationship to be built 
    		#between the @cart object and the product
    		##@line_item = @cart.line_items.build(:product => product)
			current_item = line_items.build(:product_id => product_id)
		end
		#return either the quantity or the new item
		current_item
	end

	def decrease(line_item_id)
    	current_item = line_items.find(line_item_id)
	    if current_item.quantity > 1
	      current_item.quantity -= 1
	    else
	      current_item.destroy
	    end
    current_item
  	end

  	def increase(line_item_id)
	    current_item = line_items.find(line_item_id)
	    current_item.quantity += 1
	    current_item
  	end

	#This grabs all line items and puts them into an array
	#After the array is made it sums the items in the array 
	#up using the total_price method
	def total_price
		line_items.to_a.sum { |item| item.total_price }
	end

	def total_items
		line_items.sum(:quantity)
	end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  skip_before_filter :authorize, :only => [:create, :update, :destroy]
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    #similar to try catch in ASP.NET
    begin
      @cart = Cart.find(params[:id])
      #If the cart is not found then this error catches it
    rescue ActiveRecord::RecordNotFound
      #adds the error to the log
      logger.error "Attempt to access invalid cart #{params[:id]}"
      #redirects the user to the store main page and sends
      #a flash or alert to keep through the session called
      #notice for invalid cart
      redirect_to store_url, :notice => 'Invalid cart'
    else
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @cart }
      end
    end
  end

  # GET /carts/new
  # GET /carts/new.json
  def new
    @cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/1/edit
  def edit
    @cart = Cart.find(params[:id])
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(params[:cart])

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render json: @cart, status: :created, location: @cart }
      else
        format.html { render action: "new" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /carts/1
  # PUT /carts/1.json
  def update
    @cart = Cart.find(params[:id])

    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    #finds only the current cart to destroy and not all carts
    @cart = current_cart
    #destroys the cart
    @cart.destroy
    session[:cart_id] = nil


    respond_to do |format|
      format.html { redirect_to(store_url) }
      format.json { head :ok }
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<% unless cart.line_items.empty? %>
	<table>
		<%= render(cart.line_items) %>
		<tr class="total_line">
			<td colspan="2">Total</td>
			<td class="total_cell"><%= number_to_currency(cart.total_price) %></td>
		</tr>
	</table>

<%= button_to 'Checkout', new_order_path, :method => :get %>

<%= button_to 'Empty Cart', cart, :method => :delete, :confirm => 'Are you sure?' %>

<% end %>

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @carts.each do |cart| %>
  <tr>
    <td><%= link_to 'Show', cart %></td>
    <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
    <td><%= link_to 'Destroy', cart, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<!-- <p id="notice"><%= notice %></p>
<h2>Your Pragmatic Cart</h2> -->
<!-- <div class='cart_title'>Your Cart</div>
	<table>
		<%= render(@cart.line_items) %>
		<tr class="total_line">
			<td colspan="2">Total</td>
			<td class="total_cell"><%= number_to_currency(@cart.total_price) %></td>
		</tr>
	</table>


<%= button_to 'Empty Cart', @cart, :method => :delete, :confirm => 'Are you sure?' %>
 -->

<%= render @cart %>

<!-- 
ORIGINAL CART -->
<!-- <div class='cart_title'>
	<table>
		<% @cart.line_items.each do |item| %>
		<tbody>
			<tr>
				<td><%= item.quantity %>&times;</td>
				<td><%= item.product.title %></td>
				<td class='item_price'><%= number_to_currency(item.total_price) %></td>
				<td><%= button_to 'Delete', line_item_path(item), :method => :delete %></td>
			</tr>
		</tbody>
		<% end %>
		<tr class='total_line'>
			<td colspan="2">Total</td>
			<td class="total_cell"><%= number_to_currency(@cart.total_price) %></td>
		</tr>

	</table>
</div>

<%= button_to 'Empty Cart', @cart, :method => :delete, :confirm => 'Are you sure?' %>

<%= link_to 'Edit', edit_cart_path(@cart) %> |
<%= link_to 'Back', store_path %> -->