config/routes.rb
Depot::Application.routes.draw do
  get 'admin' => 'admin#index', :as => 'admin'

  controller :sessions do
    get 'login'     => :new
    post 'login'    => :create
    delete 'logout' => :destroy
  end

  resources :users

  resources :orders

  resources :line_items do
    put 'decrease', on: :member
    put 'increase', on: :member
  end

  resources :carts

  get "store/index"

  resources :products do
    get :who_bought, :on => :member
  end

   root :to => 'store#index', :as => 'store'

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
	#Rows in the line_items table are children of 
	#rows in the carts and products tables.
	#No line item can exist unless the corresponding 
	#cart and product rows exist.
	belongs_to :product
	belongs_to :cart
	belongs_to :order

	def total_price
		#Takes the price times quantity for line item total
		product.price * quantity
	end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  skip_before_filter :authorize, :only => :create
  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @line_items }
    end
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
    @line_item = LineItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @line_item }
    end
  end

  # GET /line_items/new
  # GET /line_items/new.json
  def new
    @line_item = LineItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @line_item }
    end
  end

  # GET /line_items/1/edit
  def edit
    @line_item = LineItem.find(params[:id])
  end

  # POST /line_items
  # POST /line_items.json
  def create
    #This will find or create a cart based on applications controller method
    @cart = current_cart
    #We use params to get the product ID from the request
    #This is stored locally as no need to let view see it
    product = Product.find(params[:product_id])
    
    #Adds an item to the cart using the "add_product" 
    #function in the "cart.rb" file.
    @line_item = @cart.add_product(product.id)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to(store_url) }
        #.js is added to stop the create action from 
        #redirecting to the index display if the request is 
        #from javascript
        format.js { @current_item = @line_item }
        format.json { render json: @line_item, status: :created, location: @line_item }
      else
        format.html { render action: "new" }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /line_items/1
  # PUT /line_items/1.json
  def update
    @cart = current_cart
    #We use params to get the product ID from the request
    #This is stored locally as no need to let view see it
    product = Product.find(params[:product_id])
    
    #Adds an item to the cart using the "add_product" 
    #function in the "cart.rb" file.
    @line_item = @cart.delete_product(product.id)

    respond_to do |format|
      if @line_item.update_attributes(params[:line_item])
        format.html { redirect_to(store_url) }
        format.js { @current_item = @line_item }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    # @line_item = LineItem.find(params[:id])
    # @line_item.destroy

    @cart = current_cart
    #We use params to get the product ID from the request
    #This is stored locally as no need to let view see it
    @line_item = LineItem.find(params[:id])
    @line_item.destroy
    
    #Adds an item to the cart using the "add_product" 
    #function in the "cart.rb" file.


    respond_to do |format|
      format.html { redirect_to(store_url) }
      format.js { @current_item = @line_item }
      format.json { head :no_content }
    end
  end

  # PUT /line_items/1
  # PUT /line_items/1.json
  def decrease
    @cart = current_cart
    @line_item = @cart.decrease(params[:id])

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to(store_url) }
        format.js   { @current_item = @line_item }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def increase
    @cart = current_cart
    @line_item = @cart.increase(params[:id])

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to(store_url) }
        format.js   { @current_item = @line_item }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br />
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :cart_id %><br />
    <%= f.number_field :cart_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<% if line_item == @current_item %>
<tr id="current_item">
<% else %>
<tr>
<% end %>
	<!-- The "line_item" comes from the name of the file "_line_item" -->
	<td><%= line_item.quantity %>&times;</td>
	<td><%= line_item.product.title %></td>
	<td class='item_price'><%= number_to_currency(line_item.total_price) %></td>
	<tr>

</tr>

app/views/line_items/create.js.erb
// # $('#cart').html("<%=j render @cart %>");
// if ($('#cart tr').length == 1) {$('#cart').show('blind', 1000)};}
$("#notice").hide();

if ($("#cart tr").length == 1) { 
	$('#cart').show('blind', 1000);
}


$('#cart').html("<%= escape_javascript(render(@cart)) %>");
// # page.replace_html('cart', render(@cart))
//page[:current_item].visual_effect :highlight, :startcolor => "#88ff88", :endcolor => "#114411"

$('#current_item').css({'background-color':'#88ff88'}).animate({'background-color':'#114411'}, 1300);

// # The page variable is an instance of something called a 
// # Javascript generator(Rails class that knows how to create
// # JavaScript on the server and have it executed by browser)
// # Here we are telling it to replace the content of the element
// # on the current page with the id cart with the rendered partial
// # for a given cart. The simple RJS template tells the browser
// # to replace the content of the element whose id="cart" with
// # that HTML.

app/views/line_items/decrease.js.erb
$('#cart').html("<%= escape_javascript(render(@cart)) %>");
// # page.replace_html('cart', render(@cart))
//page[:current_item].visual_effect :highlight, :startcolor => "#88ff88", :endcolor => "#114411"

$('#current_item').css({'background-color':'#88ff88'}).animate({ backgroundColor:'#114411'}, 1300);

app/views/line_items/destroy.js.erb
$('#cart').html("<%= escape_javascript(render(@cart)) %>");

app/views/line_items/edit.html.erb
<h1>Editing line_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/increase.js.erb
//$("#notice").hide();

// if ($("#cart tr").length == 1) { 
// 	$('#cart').show('blind', 1000);
// }


$('#cart').html("<%= escape_javascript(render(@cart)) %>");
// # page.replace_html('cart', render(@cart))
//page[:current_item].visual_effect :highlight, :startcolor => "#88ff88", :endcolor => "#114411"

$('#current_item').css({'background-color':'#88ff88'}).animate({ backgroundColor:'#114411'}, 1300);

app/views/line_items/index.html.erb
<h1>Listing line_items</h1>

<table>
  <tr>
    <th>Product</th>
    <th>Cart</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @line_items.each do |line_item| %>
  <tr>
    <td><%= line_item.product_id %></td>
    <td><%= line_item.cart_id %></td>
    <td><%= link_to 'Show', line_item %></td>
    <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
    <td><%= link_to 'Destroy', line_item, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Line item', new_line_item_path %>

<!--  Goes on _line_item.html.erb

<td><%= button_to 'Delete', line_item_path(line_item), :method => :delete, :remote => :true %></td>
  <td><%= button_to 'Increase', increase_line_item_path(line_item), :remote => :true, :method => :put %></td>
  <td><%= button_to 'Decrease', decrease_line_item_path(line_item), :remote => :true, :method => :put %></td>
</tr> -->

app/views/line_items/new.html.erb
<h1>New line_item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Product:</b>
  <%= @line_item.product_id %>
</p>

<p>
  <b>Cart:</b>
  <%= @line_item.cart_id %>
</p>


<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>