config/routes.rb
Depot::Application.routes.draw do
  get 'admin' => 'admin#index', :as => 'admin'

  controller :sessions do
    get 'login'     => :new
    post 'login'    => :create
    delete 'logout' => :destroy
  end

  resources :users

  resources :orders

  resources :line_items do
    put 'decrease', on: :member
    put 'increase', on: :member
  end

  resources :carts

  get "store/index"

  resources :products do
    get :who_bought, :on => :member
  end

   root :to => 'store#index', :as => 'store'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Depot</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= stylesheet_link_tag "depot", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body id="store">
	<div id="banner">
		<%= image_tag("logo.png") %>
		<%= @page_title || "Pragmatic Bookshelf" %>
	</div>
	<div id="columns">
		<div id="side">
			<div id="cart">
				<% if @cart %>
					<%= hidden_div_if(@cart.line_items.empty?, :id => "cart") do %>
					<%= render @cart %>
					<% end %>
				<% end %>
			</div>
			<% t = Time.now %>
			<span style="color: white"><%= t.strftime("%I:%M%p") %></span> <br />
			<%= link_to 'Home', store_path %><br />
			<a href="#">Questions</a><br />
			<a href="#">News</a><br />
			<a href="#">Contact</a><br />
<!-- This is your admin only view based on session_id -->
			<% if session[:user_id] %>
				<br />
				<%= link_to 'Orders', orders_path %> <br />
				<%= link_to 'Products', products_path %> <br />
				<%= link_to 'Users', users_path %> <br />
				<br />
				<%= button_to 'Logout', logout_path, :method => :delete %>
				<% end %>
		</div>
		<div id="main">
			<%= yield %>
		</div>
	</div>
</body>
</html>